Resources:
  LambdaA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_a.app.lambda_handler
      Runtime: python3.11
      CodeUri: src/

  LambdaB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function_b.app.lambda_handler
      Runtime: python3.11
      CodeUri: src/
